# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Team
    url: 'people'
    weight: 15
  - name: Alumni
    url: 'alumni'
    weight: 17
  - name: Publications
    url: '#publications'
    weight: 20
  - name: Research
    url: '#research'
    weight: 25
  - name: Book
    url: 'book'
    weight: 30
  - name: Field Campaigns
    url: '#fieldcampaigns'
    weight: 40
  - name: Instrumentation
    url: '#instrumentation'
    weight: 50
  - name: DEI
    url: '#dei'
    weight: 30
  - name: Contact
    url: '#contact'
    weight: 90
    

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
  - name: CV
    url: media/cv.pdf
    weight: 95
